from marshmallow import Schema


class PlayerSchema(Schema):
    class Meta:
        fields = (
            'player_id',
            'team_id',
            'first_name',
            'last_name',
            'hometown_desc',
            'play_recognition',
            'press',
            'power_moves',
            'kick_accuracy',
            'redshirt',
            'year',
            'jersey_number',
            'throwing_power',
            'throwing_accuracy',
            'overall',
            'agility',
            'stamina',
            'acceleration',
            'pursuit',
            'route_running',
            'speed',
            'trucking',
            'ball_carrier_vision',
            'catch_in_traffic',
            'block_shedding',
            'strength',
            'catch',
            'injury',
            'tackling',
            'pass_blocking',
            'run_blocking',
            'break_tackle',
            'impact_blocking',
            'jump',
            'carry',
            'stiff_arm',
            'kick_power',
            'awareness',
            'release',
            'position',
            'spec_catch',
            'elusiveness',
            'height',
            'spin_move',
            'weight',
            'hit_power',
            'kick_return',
            'man_coverage',
            'zone_coverage',
            'finesse_moves',
            'juke_move',
            'games_played'
        )
